// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://loopztbkayfrtqiiewbn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxvb3B6dGJrYXlmcnRxaWlld2JuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMzU2MTksImV4cCI6MjA2OTkxMTYxOX0.T_A9czwh0nZFRpRsvt6vn_W6LFpBL1KCGpu4LC-IKdA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});